"""Auto-generated by `flask db init`.

Mark the migrations directory as a Python package so migration scripts can
import shared helpers (e.g. ``from migrations._bind_helpers import ...``)
without requiring the repo root to be on ``sys.path`` manually.

The repo root is on ``sys.path`` because the package is installed editable
(``pip install -e .[dev]``) and ``pyproject.toml`` sets ``pythonpath = ["src"]``
for pytest. In production, gunicorn is launched from
``/home/ubuntu/telemetry_server`` so the repo root is the CWD and Python adds
it to ``sys.path`` automatically.
"""
